### ISSUE TITLE
FluentBit helm chart missing a priorityClassName configuration option

### ISSUE THREAD

**Issue by itay-grudev** [coralogix/telemetry-shippers#139]
The FluentBit helm is chart missing a `priorityClassName` configuration option. This means we can't override the priority of the logging system and there is risk the FluentBit pods will be evicted at critical moments.

**Comment by amit-mazor** [comment]
Since our Fluentbit chart is based on the `official Fluentbit chart`, we are not managing the templates, but only provide you the values (with all of the best practices and required configuration to integrate with Coralogix).
 
priorityClass `is supported in the template`, See: https://github.com/fluent/helm-charts/blob/main/charts/fluent-bit/templates/_pod.tpl#L8. 

meaning you can have your own yaml file to override our values.yaml, add a priorityClass field, and it will work.
```
fluent-bit:
  priorityClassName: monitoring
```
